// Auto-generated by Tools/BoneExtractor - DO NOT EDIT
// Regenerate: cd Tools/BoneExtractor && dotnet run
#pragma once
#include <cstdint>
#include <string>
#include <unordered_map>
#include <vector>

// clang-format off

// Mirrors HitboxSlot in Tools/BoneExtractor/Models.cs.
// Order matches the slotBones array in HeroSkeletonPairs.hpp.
enum class HitboxSlot : int
{
    Head  = 0,
    Neck  = 1,
    Torso = 2,
    Arms  = 3,
    Legs  = 4,
    Count = 5,
};

inline constexpr int kHitboxSlotCount = static_cast<int>(HitboxSlot::Count);

struct BonePair
{
    int idA;
    int idB;
};

// slotBones uses a C-array instead of std::array to avoid double-brace
// requirements in MSVC aggregate initialization.
// Sorted by hitbox radius descending; empty means the slot is absent for this model.
struct ModelBoneData
{
    std::vector<BonePair>                pairs;
    std::unordered_map<std::string, int> ids;
    std::vector<int16_t>                 slotBones[kHitboxSlotCount];
};

// clang-format on
